---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iruzspa1/claroglass.cl/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp -R assets/. $DEPLOYPATH/assets/
