---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iruzspa1/public_html/claroglass.cl/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp politica-de-privacidad.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assets/. $DEPLOYPATH/assets/
